name: Run UI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.uv/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        uv sync

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y locales
        sudo locale-gen nl_NL.UTF-8
        sudo update-locale LANG=nl_NL.UTF-8

    - name: Install Playwright browsers
      run: |
        uv pip install pytest-playwright
        uv run playwright install --with-deps chromium firefox webkit

    - name: Run tests
      run: ./script/test-ui
